### ISSUE TITLE
The BDD & SAT versions do not compile. 

### ISSUE THREAD

**Issue by modulovalue** [bishoksan/DFTA#4]
Hello @jpgallagher,
Hello @bishoksan,

I'm trying to get the new BDD and SAT based implementations to run. However, due to missing dependencies, that appears not to be possible.

The BDD version depends on:

```java
import net.sf.javabdd.*;
```

and the SAT version depends on:

```java
import com.microsoft.z3.*;
```

Both of which do not resolve on my machine with the way the project is currently set-up.

There also doesn't seem to be any build scripts that could fix this issue.

I have considered setting up a new project and finding the dependencies somewhere, but I wanted to ask, before I do that, if there perhaps is something missing in this repo that would setup the dependencies correctly?

**Comment by jpgallagher** [comment]
Hello @modulovalue,

I pushed all the jarfiles including those for z3 and javabdd to the lib directory.  Note that the SAT and BDD-based versions were highly experimental.  When I originally developed them they ran but without any significant performance benefit, so I more or less gave upon them.  Now when I try them I get runtime problems from z3.  So I am not sure what the problem is.

**Comment by modulovalue** [comment]
I've managed to get the imports to resolve with the jars that you've provided. Thank you for your help @jpgallagher!
